### ISSUE TITLE
Potential error in `BaseSynthetixBridge` unit test

### ISSUE THREAD

**Issue by Wodann** [Synthetixio/synthetix#2210]
While upgrading Hardhat, we were testing our development-version of Hardhat with `synthetix` and noticed that there is a test failure which seems to be the result of a previous bug in Hardhat.

```
1) Contract: BaseSynthetixBridge (unit tests)
       when all the deps are mocked
         when the target is deployed and the proxy is set
           initiateSynthTransfer
             fails if synth is not enabled:
     AssertionError: expected 'VM Exception while processing transac…' to include 'Transaction reverted without a reason…'
      at Object.assertRevert [as revert] (test/utils/index.js:495:12)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Context.<anonymous> (test/contracts/BaseSynthetixBridge.unit.js:207:6)
```

It is our understanding that the transaction should revert with a reason string, but for some reason would show up with a "reverted without a reason" error. This should be fixed in the next version of Hardhat.

If this is not the behaviour that you'd expect from Hardhat, please let us know [here](https://github.com/NomicFoundation/edr/issues/254#issuecomment-1965145523).

**Comment by ibrahim1023** [comment]
Hey! For me, all tests under BaseSynthetixBridge contract seems to be passing fine
